title: My first GitHub Pages page
author: Kalani M.
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Here is a basic description of this site. 
  It is a GitHub site that will have minimal content. 
  Check back whenever, but I wouldn't expect too much from this particular site.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
